"""
Text chunking strategies for the RAG pipeline.

Each chunker takes extracted text and returns a list of Chunk objects
with metadata. All chunkers share the same return type for uniformity
in the Phase 1 pre-grid.

Citations:
  - _instructions.md L602 (3 chunking strategies)
  - _instructions.md L604 (metadata: page number, method, size params, unique ID)
  - _instructions.md L605 (no mid-word/mid-sentence splits)
"""

import re
from collections.abc import Callable, Mapping
from typing import Any

from src.models import Chunk, ChunkMetadata, PolicyDocumentMetadata

# Cache spaCy docs to avoid re-parsing the same text across size/overlap combos
_spacy_cache: dict[int, tuple[list[str], list]] = {}
_nlp = None


# Legal-policy heading detection works best on Markdown generated by a
# layout-aware parser, but also tolerates plain extracted text.
_LEGAL_HEADING_PATTERNS: list[tuple[int, re.Pattern[str]]] = [
    (
        1,
        re.compile(
            r"^(?:#{1,6}\s*)?(?:"
            r"(?:chapter|chap\.?)\s+[\w.\-]+"
            r"|(?:chapitre)\s+[\w.\-]+"
            r"|(?:cap[ií]tulo)\s+[\w.\-]+"
            r"|(?:part|title|t[ií]tulo)\s+[\w.\-]+"
            r"|第\s*[一二三四五六七八九十百千万\d]+\s*章"
            r").*$",
            re.IGNORECASE,
        ),
    ),
    (
        2,
        re.compile(
            r"^(?:#{1,6}\s*)?(?:"
            r"article\s+[\w.\-]+"
            r"|art[ií]culo\s+[\w.\-]+"
            r"|artigo\s+[\w.\-]+"
            r"|rule\s+[\w.\-]+"
            r"|regulation\s+[\w.\-]+"
            r"|第\s*[一二三四五六七八九十百千万\d]+\s*条"
            r").*$",
            re.IGNORECASE,
        ),
    ),
    (
        3,
        re.compile(
            r"^(?:#{1,6}\s*)?(?:"
            r"section\s+[\w.\-]+"
            r"|sec\.\s*[\w.\-]+"
            r"|subsection\s+[\w.\-]+"
            r"|clause\s+[\w.\-]+"
            r"|paragraph\s+[\w.\-]+"
            r"|secci[oó]n\s+[\w.\-]+"
            r"|se[cç][aã]o\s+[\w.\-]+"
            r"|第\s*[一二三四五六七八九十百千万\d]+\s*款"
            r").*$",
            re.IGNORECASE,
        ),
    ),
]

_MARKDOWN_HEADING_RE = re.compile(r"^#{1,6}\s+")


def _coerce_document_metadata(
    document_metadata: PolicyDocumentMetadata | Mapping[str, Any] | None,
) -> dict[str, Any]:
    """Normalize document-level metadata into a plain dict."""
    if document_metadata is None:
        return {}
    if isinstance(document_metadata, PolicyDocumentMetadata):
        return document_metadata.chunk_metadata_fields()
    return {key: value for key, value in dict(document_metadata).items() if value is not None}


def _normalize_heading(raw_heading: str) -> str:
    """Strip Markdown/bullet noise while preserving the legal label."""
    heading = _MARKDOWN_HEADING_RE.sub("", raw_heading.strip())
    heading = re.sub(r"^[\-\*\u2022]\s+", "", heading)
    heading = re.sub(r"\s+", " ", heading)
    return heading.strip(" :：.-")


def extract_legal_hierarchy(text: str, end_char: int | None = None) -> str | None:
    """Return the most specific legal hierarchy visible before ``end_char``.

    Examples:
        Chapter 3 > Article 12 > Section 3
        Capítulo 2 > Artículo 8 > Sección 4
        第三章 > 第十二条 > 第三款
    """
    scan_text = text[:end_char] if end_char is not None else text
    hierarchy: dict[int, str] = {}

    for line in scan_text.splitlines():
        stripped = _normalize_heading(line)
        if not stripped:
            continue

        for level, pattern in _LEGAL_HEADING_PATTERNS:
            if pattern.match(stripped):
                hierarchy[level] = stripped
                for deeper in [candidate for candidate in hierarchy if candidate > level]:
                    del hierarchy[deeper]
                break

    if not hierarchy:
        return None
    return " > ".join(hierarchy[level] for level in sorted(hierarchy))


def _make_chunk_metadata(
    chunk_size: int,
    overlap: int,
    parser: str,
    document_metadata: PolicyDocumentMetadata | Mapping[str, Any] | None = None,
    legal_hierarchy: str | None = None,
) -> ChunkMetadata:
    """Build per-chunk metadata with document fields and legal hierarchy."""
    payload = _coerce_document_metadata(document_metadata)
    payload.update({
        "chunk_size": chunk_size,
        "overlap": overlap,
        "parser": parser,
    })
    if legal_hierarchy:
        payload["legal_hierarchy"] = legal_hierarchy
    return ChunkMetadata(**payload)


def _sent_tokenize(text: str) -> list[str]:
    """Sentence tokenizer with an NLTK path and a conservative regex fallback."""
    try:
        import nltk
        from nltk.tokenize import sent_tokenize

        nltk.download("punkt_tab", quiet=True)
        return sent_tokenize(text)
    except Exception:
        return [
            sentence.strip()
            for sentence in re.split(r"(?<=[.!?。！？])\s+", text.strip())
            if sentence.strip()
        ]


def _get_spacy_model():
    """Load the spaCy vector model only when semantic chunking is requested."""
    global _nlp
    if _nlp is not None:
        return _nlp

    import spacy

    _nlp = spacy.load("en_core_web_md")
    return _nlp


def _get_spacy_sentences(text: str) -> tuple[list[str], list]:
    """Parse text with spaCy once, cache and reuse across calls."""
    key = hash(text)
    if key in _spacy_cache:
        return _spacy_cache[key]

    doc = _get_spacy_model()(text)
    sent_spans = [sent for sent in doc.sents if sent.text.strip()]
    sentences = [sent.text.strip() for sent in sent_spans]
    _spacy_cache[key] = (sentences, sent_spans)
    return sentences, sent_spans


_LEXICAL_STOPWORDS = {
    "the", "a", "an", "and", "or", "of", "to", "in", "on", "for", "with",
    "by", "from", "at", "as", "is", "are", "was", "were", "be", "been",
    "this", "that", "these", "those", "it", "its", "their", "into", "due",
}


def _token_set(sentence: str) -> set[str]:
    """Token set for the semantic fallback path."""
    return {
        token
        for token in re.findall(r"[a-zA-Z][a-zA-Z\-]{2,}", sentence.lower())
        if token not in _LEXICAL_STOPWORDS
    }


def _lexical_boundary_indices(sentences: list[str], threshold: float = 0.08) -> list[int]:
    """Detect topic shifts without spaCy by comparing adjacent token sets."""
    boundaries: list[int] = []
    for index in range(1, len(sentences)):
        previous = _token_set(sentences[index - 1])
        current = _token_set(sentences[index])
        if not previous or not current:
            continue
        similarity = len(previous & current) / len(previous | current)
        if similarity < threshold:
            boundaries.append(index)
    return boundaries


def _build_semantic_chunks(
    text: str,
    page_number: int,
    chunk_size: int,
    overlap: int,
    parser: str,
    sentences: list[str],
    boundary_indices: list[int],
    document_metadata: PolicyDocumentMetadata | Mapping[str, Any] | None = None,
) -> list[Chunk]:
    """Build semantic Chunk objects from sentences and boundary indices."""
    chunks: list[Chunk] = []
    chunk_index = 0

    # Add start and end as implicit boundaries
    all_boundaries = [0] + boundary_indices + [len(sentences)]

    i = 0
    while i < len(all_boundaries) - 1:
        start_sent = all_boundaries[i]
        end_sent = all_boundaries[i + 1]
        group = sentences[start_sent:end_sent]

        # If this group exceeds chunk_size, split further at chunk_size
        current_sentences: list[str] = []
        current_len = 0

        for sent in group:
            new_len = current_len + len(sent) + (1 if current_sentences else 0)

            if current_sentences and new_len > chunk_size:
                # Flush current chunk
                chunk_text = " ".join(current_sentences)
                start_char = text.find(current_sentences[0])
                last_sent = current_sentences[-1]
                end_char = text.find(last_sent, start_char) + len(last_sent)
                legal_hierarchy = extract_legal_hierarchy(text, end_char=end_char)
                metadata = _make_chunk_metadata(
                    chunk_size=chunk_size,
                    overlap=overlap,
                    parser=parser,
                    document_metadata=document_metadata,
                    legal_hierarchy=legal_hierarchy,
                )

                chunks.append(Chunk(
                    text=chunk_text,
                    page_number=page_number,
                    chunk_index=chunk_index,
                    start_char=max(start_char, 0),
                    end_char=max(end_char, 1),
                    method="semantic",
                    metadata=metadata,
                ))
                chunk_index += 1
                current_sentences = []
                current_len = 0

            current_sentences.append(sent)
            current_len = current_len + len(sent) + (1 if len(current_sentences) > 1 else 0)

        # Flush remaining sentences in this group
        if current_sentences:
            chunk_text = " ".join(current_sentences)
            start_char = text.find(current_sentences[0])
            last_sent = current_sentences[-1]
            end_char = text.find(last_sent, start_char) + len(last_sent)
            legal_hierarchy = extract_legal_hierarchy(text, end_char=end_char)
            metadata = _make_chunk_metadata(
                chunk_size=chunk_size,
                overlap=overlap,
                parser=parser,
                document_metadata=document_metadata,
                legal_hierarchy=legal_hierarchy,
            )

            chunks.append(Chunk(
                text=chunk_text,
                page_number=page_number,
                chunk_index=chunk_index,
                start_char=max(start_char, 0),
                end_char=max(end_char, 1),
                method="semantic",
                metadata=metadata,
            ))
            chunk_index += 1

        i += 1

    return chunks


def chunk_fixed_size(
    text: str,
    page_number: int,
    chunk_size: int,
    overlap: int,
    parser: str,
    document_metadata: PolicyDocumentMetadata | Mapping[str, Any] | None = None,
) -> list[Chunk]:
    """Split text into fixed-size chunks with word-boundary awareness.

    Args:
        text: The source text to chunk.
        page_number: Page number this text came from.
        chunk_size: Target chunk size in characters.
        overlap: Number of characters to overlap between consecutive chunks.
        parser: Name of the PDF parser used (for metadata).
        document_metadata: Optional policy metadata injected into every chunk.

    Returns:
        List of Chunk objects with metadata and character offsets.
    """
    if not text or not text.strip():
        return []

    chunks: list[Chunk] = []
    start = 0
    chunk_index = 0

    while start < len(text):
        end = start + chunk_size

        if end >= len(text):
            # Last chunk — take the rest
            end = len(text)
        else:
            # Back up to the nearest word boundary (space)
            boundary = text.rfind(" ", start, end)
            if boundary > start:
                end = boundary

        chunk_text = text[start:end]

        # Skip chunks that are only whitespace
        if chunk_text.strip():
            legal_hierarchy = extract_legal_hierarchy(text, end_char=end)
            metadata = _make_chunk_metadata(
                chunk_size=chunk_size,
                overlap=overlap,
                parser=parser,
                document_metadata=document_metadata,
                legal_hierarchy=legal_hierarchy,
            )
            chunks.append(Chunk(
                text=chunk_text,
                page_number=page_number,
                chunk_index=chunk_index,
                start_char=start,
                end_char=end,
                method="fixed_size",
                metadata=metadata,
            ))
            chunk_index += 1

        # Advance by (end - start - overlap), but at least 1 char to avoid infinite loop
        step = max(end - start - overlap, 1)
        start = start + step

    return chunks


def chunk_sentence(
    text: str,
    page_number: int,
    chunk_size: int,
    overlap: int,
    parser: str,
    document_metadata: PolicyDocumentMetadata | Mapping[str, Any] | None = None,
) -> list[Chunk]:
    """Split text into chunks at sentence boundaries using NLTK.

    Groups consecutive sentences until adding the next sentence would
    exceed chunk_size. Overlap is handled by repeating trailing sentences
    from the previous chunk.

    Args:
        text: The source text to chunk.
        page_number: Page number this text came from.
        chunk_size: Target chunk size in characters.
        overlap: Approximate character overlap — determines how many trailing
                 sentences from the previous chunk to repeat.
        parser: Name of the PDF parser used (for metadata).
        document_metadata: Optional policy metadata injected into every chunk.

    Returns:
        List of Chunk objects with metadata.
    """
    if not text or not text.strip():
        return []

    sentences = _sent_tokenize(text)
    if not sentences:
        return []

    chunks: list[Chunk] = []
    chunk_index = 0

    i = 0  # index into sentences list
    while i < len(sentences):
        # Build a chunk by accumulating sentences
        current_sentences: list[str] = []
        current_len = 0

        while i < len(sentences):
            sent = sentences[i]
            new_len = current_len + len(sent) + (1 if current_sentences else 0)

            # If adding this sentence would exceed chunk_size and we already
            # have at least one sentence, stop here
            if current_sentences and new_len > chunk_size:
                break

            current_sentences.append(sent)
            current_len = new_len
            i += 1

        chunk_text = " ".join(current_sentences)

        # Find the chunk's position in the original text
        start_char = text.find(current_sentences[0])
        last_sent = current_sentences[-1]
        end_char = text.find(last_sent, start_char) + len(last_sent)
        legal_hierarchy = extract_legal_hierarchy(text, end_char=end_char)
        metadata = _make_chunk_metadata(
            chunk_size=chunk_size,
            overlap=overlap,
            parser=parser,
            document_metadata=document_metadata,
            legal_hierarchy=legal_hierarchy,
        )

        chunks.append(Chunk(
            text=chunk_text,
            page_number=page_number,
            chunk_index=chunk_index,
            start_char=max(start_char, 0),
            end_char=max(end_char, 1),
            method="sentence",
            metadata=metadata,
        ))
        chunk_index += 1

        # Handle overlap: back up by enough sentences to cover ~overlap chars
        # but always advance at least 1 sentence to prevent infinite loops
        if overlap > 0 and i < len(sentences):
            overlap_chars = 0
            backtrack = 0
            max_backtrack = len(current_sentences) - 1  # keep at least 1 sentence of progress
            for j in range(len(current_sentences) - 1, -1, -1):
                if backtrack >= max_backtrack:
                    break
                overlap_chars += len(current_sentences[j])
                backtrack += 1
                if overlap_chars >= overlap:
                    break
            i = i - backtrack

    return chunks


def chunk_semantic(
    text: str,
    page_number: int,
    chunk_size: int,
    overlap: int,
    parser: str,
    similarity_threshold: float = 0.5,
    document_metadata: PolicyDocumentMetadata | Mapping[str, Any] | None = None,
) -> list[Chunk]:
    """Split text at semantic boundaries detected via spaCy word vectors.

    Algorithm:
    1. Split text into sentences using spaCy's sentence segmentation.
    2. Compute cosine similarity between consecutive sentence pairs.
    3. Mark a boundary where similarity drops below the threshold.
    4. Group sentences between boundaries into chunks, respecting chunk_size.

    Args:
        text: The source text to chunk.
        page_number: Page number this text came from.
        chunk_size: Target max chunk size in characters.
        overlap: Approximate character overlap (sentence-level backtrack).
        parser: Name of the PDF parser used (for metadata).
        similarity_threshold: Cosine similarity below which a boundary is placed.
        document_metadata: Optional policy metadata injected into every chunk.

    Returns:
        List of Chunk objects split at semantic boundaries.
    """
    if not text or not text.strip():
        return []

    # Single spaCy parse per unique text — cached across size/overlap combos.
    # If spaCy or the vector model is not installed, fall back to a lightweight
    # lexical topic-shift detector so non-semantic pipeline paths remain usable.
    try:
        sentences, sent_spans = _get_spacy_sentences(text)
    except (ImportError, OSError):
        sentences = _sent_tokenize(text)
        if not sentences:
            return []
        boundary_indices = _lexical_boundary_indices(sentences)
        return _build_semantic_chunks(
            text=text,
            page_number=page_number,
            chunk_size=chunk_size,
            overlap=overlap,
            parser=parser,
            sentences=sentences,
            boundary_indices=boundary_indices,
            document_metadata=document_metadata,
        )

    if not sent_spans:
        return []

    # Compute similarity between consecutive sentence spans and find boundaries
    # No second _nlp() call — spans already have vectors from the doc parse
    boundary_indices: list[int] = []
    for i in range(1, len(sent_spans)):
        if not sent_spans[i - 1].has_vector or not sent_spans[i].has_vector:
            continue
        sim = sent_spans[i - 1].similarity(sent_spans[i])
        if sim < similarity_threshold:
            boundary_indices.append(i)

    return _build_semantic_chunks(
        text=text,
        page_number=page_number,
        chunk_size=chunk_size,
        overlap=overlap,
        parser=parser,
        sentences=sentences,
        boundary_indices=boundary_indices,
        document_metadata=document_metadata,
    )


def chunk_policy_document(
    pages: list[tuple[int, str]],
    chunk_size: int = 500,
    overlap: int = 0,
    parser: str = "layout_markdown",
    document_metadata: PolicyDocumentMetadata | Mapping[str, Any] | None = None,
    chunker: str = "sentence",
) -> list[Chunk]:
    """Chunk a parsed policy document with compliance metadata injection.

    This is the recommended ingestion path for the credit-policy library:
    sentence splitting, 500-character chunks, zero overlap, and metadata
    ready for hard filters.
    """
    chunkers: dict[str, Callable[..., list[Chunk]]] = {
        "fixed_size": chunk_fixed_size,
        "sentence": chunk_sentence,
        "semantic": chunk_semantic,
    }
    if chunker not in chunkers:
        raise ValueError(f"Unknown chunker: {chunker}")

    all_chunks: list[Chunk] = []
    last_hierarchy: str | None = None
    base_metadata = _coerce_document_metadata(document_metadata)

    for page_number, page_text in pages:
        if not page_text.strip():
            continue

        page_metadata = dict(base_metadata)
        if last_hierarchy and "legal_hierarchy" not in page_metadata:
            page_metadata["legal_hierarchy"] = last_hierarchy

        page_chunks = chunkers[chunker](
            text=page_text,
            page_number=page_number,
            chunk_size=chunk_size,
            overlap=overlap,
            parser=parser,
            document_metadata=page_metadata,
        )
        for chunk in page_chunks:
            if chunk.metadata.legal_hierarchy:
                last_hierarchy = chunk.metadata.legal_hierarchy
            all_chunks.append(chunk)

    return all_chunks
